(function(global,factory){typeof exports==='object'&&typeof module!=='undefined'?module.exports=factory(require('video.js')):typeof define==='function'&&define.amd?define(['video.js'],factory):(global.videojsFlash=factory(global.videojs));}(this,(function(videojs){'use strict';videojs='default'in videojs?videojs['default']:videojs;var version="5.4.1";var version$1="2.0.1";function FlashRtmpDecorator(Flash){Flash.streamingFormats={'rtmp/mp4':'MP4','rtmp/flv':'FLV'};Flash.streamFromParts=function(connection,stream){return connection+'&'+ stream;};Flash.streamToParts=function(src){var parts={connection:'',stream:''};if(!src){return parts;}
var connEnd=src.search(/&(?!\w+=)/);var streamBegin=void 0;if(connEnd!==-1){streamBegin=connEnd+ 1;}else{connEnd=streamBegin=src.lastIndexOf('/')+ 1;if(connEnd===0){connEnd=streamBegin=src.length;}}
parts.connection=src.substring(0,connEnd);parts.stream=src.substring(streamBegin,src.length);return parts;};Flash.isStreamingType=function(srcType){return srcType in Flash.streamingFormats;};Flash.RTMP_RE=/^rtmp[set]?:\/\//i;Flash.isStreamingSrc=function(src){return Flash.RTMP_RE.test(src);};Flash.rtmpSourceHandler={};Flash.rtmpSourceHandler.canPlayType=function(type){if(Flash.isStreamingType(type)){return'maybe';}
return'';};Flash.rtmpSourceHandler.canHandleSource=function(source,options){var can=Flash.rtmpSourceHandler.canPlayType(source.type);if(can){return can;}
if(Flash.isStreamingSrc(source.src)){return'maybe';}
return'';};Flash.rtmpSourceHandler.handleSource=function(source,tech,options){var srcParts=Flash.streamToParts(source.src);tech.setRtmpConnection(srcParts.connection);tech.setRtmpStream(srcParts.stream);};Flash.registerSourceHandler(Flash.rtmpSourceHandler);return Flash;}
var commonjsGlobal=typeof window!=='undefined'?window:typeof global!=='undefined'?global:typeof self!=='undefined'?self:{};var win;if(typeof window!=="undefined"){win=window;}else if(typeof commonjsGlobal!=="undefined"){win=commonjsGlobal;}else if(typeof self!=="undefined"){win=self;}else{win={};}
var window_1=win;var classCallCheck=function(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}};var inherits=function(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+ typeof superClass);}
subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass;};var possibleConstructorReturn=function(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}
return call&&(typeof call==="object"||typeof call==="function")?call:self;};var Tech=videojs.getComponent('Tech');var Dom=videojs.dom;var Url=videojs.url;var createTimeRange=videojs.createTimeRange;var mergeOptions=videojs.mergeOptions;var navigator=window_1&&window_1.navigator||{};var Flash=function(_Tech){inherits(Flash,_Tech);function Flash(options,ready){classCallCheck(this,Flash);var _this=possibleConstructorReturn(this,_Tech.call(this,options,ready));if(options.source){_this.ready(function(){this.setSource(options.source);},true);}
if(options.startTime){_this.ready(function(){this.load();this.play();this.currentTime(options.startTime);},true);}
window_1.videojs=window_1.videojs||{};window_1.videojs.Flash=window_1.videojs.Flash||{};window_1.videojs.Flash.onReady=Flash.onReady;window_1.videojs.Flash.onEvent=Flash.onEvent;window_1.videojs.Flash.onError=Flash.onError;_this.on('seeked',function(){this.lastSeekTarget_=undefined;});return _this;}
Flash.prototype.createEl=function createEl(){var options=this.options_;if(!options.swf){options.swf='//vjs.zencdn.net/swf/'+ version+'/video-js.swf';}
var objId=options.techId;var flashVars=mergeOptions({readyFunction:'videojs.Flash.onReady',eventProxyFunction:'videojs.Flash.onEvent',errorEventProxyFunction:'videojs.Flash.onError',autoplay:options.autoplay,preload:options.preload,loop:options.loop,muted:options.muted},options.flashVars);var params=mergeOptions({wmode:'opaque',bgcolor:'#000000'},options.params);var attributes=mergeOptions({id:objId,name:objId,'class':'vjs-tech'},options.attributes);this.el_=Flash.embed(options.swf,flashVars,params,attributes);this.el_.tech=this;return this.el_;};Flash.prototype.play=function play(){if(this.ended()){this.setCurrentTime(0);}
this.el_.vjs_play();};Flash.prototype.pause=function pause(){this.el_.vjs_pause();};Flash.prototype.src=function src(_src){if(_src===undefined){return this.currentSrc();}
return this.setSrc(_src);};Flash.prototype.setSrc=function setSrc(src){var _this2=this;src=Url.getAbsoluteURL(src);this.el_.vjs_src(src);if(this.autoplay()){this.setTimeout(function(){return _this2.play();},0);}};Flash.prototype.seeking=function seeking(){return this.lastSeekTarget_!==undefined;};Flash.prototype.setCurrentTime=function setCurrentTime(time){var seekable=this.seekable();if(seekable.length){time=time>seekable.start(0)?time:seekable.start(0);time=time<seekable.end(seekable.length- 1)?time:seekable.end(seekable.length- 1);this.lastSeekTarget_=time;this.trigger('seeking');this.el_.vjs_setProperty('currentTime',time);_Tech.prototype.setCurrentTime.call(this);}};Flash.prototype.currentTime=function currentTime(){if(this.seeking()){return this.lastSeekTarget_||0;}
return this.el_.vjs_getProperty('currentTime');};Flash.prototype.currentSrc=function currentSrc(){if(this.currentSource_){return this.currentSource_.src;}
return this.el_.vjs_getProperty('currentSrc');};Flash.prototype.duration=function duration(){if(this.readyState()===0){return NaN;}
var duration=this.el_.vjs_getProperty('duration');return duration>=0?duration:Infinity;};Flash.prototype.load=function load(){this.el_.vjs_load();};Flash.prototype.poster=function poster(){this.el_.vjs_getProperty('poster');};Flash.prototype.setPoster=function setPoster(){};Flash.prototype.seekable=function seekable(){var duration=this.duration();if(duration===0){return createTimeRange();}
return createTimeRange(0,duration);};Flash.prototype.buffered=function buffered(){var ranges=this.el_.vjs_getProperty('buffered');if(ranges.length===0){return createTimeRange();}
return createTimeRange(ranges[0][0],ranges[0][1]);};Flash.prototype.supportsFullScreen=function supportsFullScreen(){return false;};Flash.prototype.enterFullScreen=function enterFullScreen(){return false;};Flash.prototype.getVideoPlaybackQuality=function getVideoPlaybackQuality(){var videoPlaybackQuality=this.el_.vjs_getProperty('getVideoPlaybackQuality');if(window_1.performance&&typeof window_1.performance.now==='function'){videoPlaybackQuality.creationTime=window_1.performance.now();}else if(window_1.performance&&window_1.performance.timing&&typeof window_1.performance.timing.navigationStart==='number'){videoPlaybackQuality.creationTime=window_1.Date.now()- window_1.performance.timing.navigationStart;}
return videoPlaybackQuality;};return Flash;}(Tech);var _readWrite=['rtmpConnection','rtmpStream','preload','defaultPlaybackRate','playbackRate','autoplay','loop','controls','volume','muted','defaultMuted'];var _readOnly=['networkState','readyState','initialTime','startOffsetTime','paused','ended','videoWidth','videoHeight'];var _api=Flash.prototype;function _createSetter(attr){var attrUpper=attr.charAt(0).toUpperCase()+ attr.slice(1);_api['set'+ attrUpper]=function(val){return this.el_.vjs_setProperty(attr,val);};}
function _createGetter(attr){_api[attr]=function(){return this.el_.vjs_getProperty(attr);};}
for(var i=0;i<_readWrite.length;i++){_createGetter(_readWrite[i]);_createSetter(_readWrite[i]);}
for(var _i=0;_i<_readOnly.length;_i++){_createGetter(_readOnly[_i]);}
Flash.isSupported=function(){return Flash.version()[0]>=10;};Tech.withSourceHandlers(Flash);Flash.nativeSourceHandler={};Flash.nativeSourceHandler.canPlayType=function(type){if(type in Flash.formats){return'maybe';}
return'';};Flash.nativeSourceHandler.canHandleSource=function(source,options){var type=void 0;function guessMimeType(src){var ext=Url.getFileExtension(src);if(ext){return'video/'+ ext;}
return'';}
if(!source.type){type=guessMimeType(source.src);}else{type=source.type.replace(/;.*/,'').toLowerCase();}
return Flash.nativeSourceHandler.canPlayType(type);};Flash.nativeSourceHandler.handleSource=function(source,tech,options){tech.setSrc(source.src);};Flash.nativeSourceHandler.dispose=function(){};Flash.registerSourceHandler(Flash.nativeSourceHandler);Flash.formats={'video/flv':'FLV','video/x-flv':'FLV','video/mp4':'MP4','video/m4v':'MP4'};Flash.onReady=function(currSwf){var el=Dom.$('#'+ currSwf);var tech=el&&el.tech;if(tech&&tech.el()){Flash.checkReady(tech);}};Flash.checkReady=function(tech){if(!tech.el()){return;}
if(tech.el().vjs_getProperty){tech.triggerReady();}else{this.setTimeout(function(){Flash.checkReady(tech);},50);}};Flash.onEvent=function(swfID,eventName){var tech=Dom.$('#'+ swfID).tech;var args=Array.prototype.slice.call(arguments,2);tech.setTimeout(function(){tech.trigger(eventName,args);},1);};Flash.onError=function(swfID,err){var tech=Dom.$('#'+ swfID).tech;if(err==='srcnotfound'){return tech.error(4);}
tech.error('FLASH: '+ err);};Flash.version=function(){var version$$1='0,0,0';try{version$$1=new window_1.ActiveXObject('ShockwaveFlash.ShockwaveFlash').GetVariable('$version').replace(/\D+/g,',').match(/^,?(.+),?$/)[1];}catch(e){try{if(navigator.mimeTypes['application/x-shockwave-flash'].enabledPlugin){version$$1=(navigator.plugins['Shockwave Flash 2.0']||navigator.plugins['Shockwave Flash']).description.replace(/\D+/g,',').match(/^,?(.+),?$/)[1];}}catch(err){}}
return version$$1.split(',');};Flash.embed=function(swf,flashVars,params,attributes){var code=Flash.getEmbedCode(swf,flashVars,params,attributes);var obj=Dom.createEl('div',{innerHTML:code}).childNodes[0];return obj;};Flash.getEmbedCode=function(swf,flashVars,params,attributes){var objTag='<object type="application/x-shockwave-flash" ';var flashVarsString='';var paramsString='';var attrsString='';if(flashVars){Object.getOwnPropertyNames(flashVars).forEach(function(key){flashVarsString+=key+'='+ flashVars[key]+'&amp;';});}
params=mergeOptions({movie:swf,flashvars:flashVarsString,allowScriptAccess:'always',allowNetworking:'all'},params);Object.getOwnPropertyNames(params).forEach(function(key){paramsString+='<param name="'+ key+'" value="'+ params[key]+'" />';});attributes=mergeOptions({data:swf,width:'100%',height:'100%'},attributes);Object.getOwnPropertyNames(attributes).forEach(function(key){attrsString+=key+'="'+ attributes[key]+'" ';});return''+ objTag+ attrsString+'>'+ paramsString+'</object>';};FlashRtmpDecorator(Flash);if(Tech.getTech('Flash')){videojs.log.warn('Not using videojs-flash as it appears to already be registered');videojs.log.warn('videojs-flash should only be used with video.js@6 and above');}else{videojs.registerTech('Flash',Flash);}
Flash.VERSION=version$1;return Flash;})));